import { NextRequest, NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';
import { sendOTP } from '@/lib/sms';

/**
 * POST /api/otp/send
 * Sends an OTP code to the provided phone number via SMS
 */
export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { phone } = body;

        // Validate phone number
        if (!phone || typeof phone !== 'string') {
            return NextResponse.json(
                { error: 'Phone number is required' },
                { status: 400 }
            );
        }

        // Clean phone number
        const cleanPhone = phone.replace(/[\s-]/g, '');

        // Generate 6-digit OTP
        const otpCode = Math.floor(100000 + Math.random() * 900000).toString();

        // Check if user exists
        const { data: existingUser, error: fetchError } = await supabase
            .from('users')
            .select('id')
            .eq('phone', cleanPhone)
            .maybeSingle();

        if (fetchError) {
            console.error('Error fetching user:', fetchError);
            return NextResponse.json(
                { error: 'Database error occurred' },
                { status: 500 }
            );
        }

        // Update or create user with OTP
        if (existingUser) {
            // Update existing user with new OTP
            const { error: updateError } = await supabase
                .from('users')
                .update({ otp_code: otpCode })
                .eq('phone', cleanPhone);

            if (updateError) {
                console.error('Error updating OTP:', updateError);
                return NextResponse.json(
                    { error: 'Failed to generate OTP' },
                    { status: 500 }
                );
            }
        } else {
            // Create new user - let Supabase generate UUID automatically
            // Don't specify 'id' field, let the database default handle it
            const { error: insertError } = await supabase
                .from('users')
                .insert({
                    phone: cleanPhone,
                    otp_code: otpCode,
                    // ID will be auto-generated by Supabase using uuid_generate_v4()
                });

            if (insertError) {
                // Handle race condition: if user was created between check and insert
                if (insertError.code === '23505') {
                    // Duplicate phone number - user was created, just update OTP
                    const { error: updateError } = await supabase
                        .from('users')
                        .update({ otp_code: otpCode })
                        .eq('phone', cleanPhone);

                    if (updateError) {
                        console.error('Error updating OTP after race condition:', updateError);
                        return NextResponse.json(
                            { error: 'Failed to generate OTP' },
                            { status: 500 }
                        );
                    }
                } else {
                    console.error('Error creating user:', insertError);
                    return NextResponse.json(
                        { error: 'Failed to create user account' },
                        { status: 500 }
                    );
                }
            }
        }

        // Send OTP via SMS
        const smsResult = await sendOTP(cleanPhone, otpCode);

        if (!smsResult.success) {
            console.error('SMS sending failed:', smsResult.error);
            // Still return success to user, but log the error
            // In production, you might want to handle this differently
            return NextResponse.json(
                {
                    error: 'Failed to send SMS. Please try again later.',
                    details: smsResult.error
                },
                { status: 500 }
            );
        }

        return NextResponse.json({
            success: true,
            message: 'OTP sent successfully',
            recipients: smsResult.recipients,
        });
    } catch (error: any) {
        console.error('Error in send OTP endpoint:', error);
        return NextResponse.json(
            { error: error.message || 'Internal server error' },
            { status: 500 }
        );
    }
}

